# Makemore part 2: Multi Layer Perceptron approach

This notebook contains my notes (ah, [hello](www.bazcuervo.net)) from Karpathy's [second lesson](https://www.youtube.com/watch?v=TCH_1BHY58I) from [*Neural Networks: Zero to Hero*](https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ).

It's more exhaustive than the [notebook](https://github.com/karpathy/nn-zero-to-hero/blob/master/lectures/makemore/makemore_part2_mlp.ipynb) that he has uploaded, given that here I reproduce all the steps in the tutorial instead of just building the final result (the process is quite iterative).

## INTRO

We'll be following the approach introduced in [A Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf), in which instead of going from the purely statistical approach to predicting words / characters, they follow an embedding + MLP approach. It's not the first paper that introduced that idea, but it's one of the most cited and populars when it comes to it. 

In the paper they use **words instead of characters**, but we'll analogously apply this approach with characters. 

## Load modules, data and build character-index mappings

In [1]:
import torch

%matplotlib inline

We'll use the same dataset of names as in all of the other lessons.

In [2]:
words = open("../data/names.txt", "r").read().splitlines()

In [3]:
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [68]:
len(''.join(words))

196113

In [4]:
len(words)

32033

As in the previous lesson, we'll build the mappings of character-index and index-character. This is the way of working with characters numerically.

In [5]:
unique_characters: list[str] = sorted(list(set("".join(words))))
# character_to_index
ctoi = {c: i + 1 for i, c in enumerate(unique_characters)}
# for the special value "." (beginnings and ends of words) we'll assign the integer 0
ctoi["."] = 0
# and the reverse counterpart, to be able to get the corresponding character to a given index
itoc = {i: c for c, i in ctoi.items()}

In [6]:
ctoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [7]:
itoc

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

## Build the dataset

Now that we have the words, we have to build our dataset: the `X` and `Y` tensors that will make the input-output pairs, that will let us train out NN and get the proper weights.

In [11]:
# context length: how many characters do we take to predict the next one?
block_size = 3
X, Y = [], []

for w in words[:4]:
    print(w)
    # first we fill the context with all zeros (the character ".")
    context = [0] * block_size

    # we iterate over each character in the given word
    for ch in w + ".":
        # we get the index of the character
        ix = ctoi[ch]
        # and given the existing context that we have (i.e. previous characters that we read in this word),
        # we use that pair context-character to create an X-Y value in our dataset (input-output)
        X.append(context)
        # (remember that context is a set of indexes as well)
        Y.append(ix)
        # for printing, we convert them into characters instead of indexes
        print("".join(itoc[i] for i in context), "--->", itoc[ix])
        # finally, we append this given character to the context and slice that context so that its size
        # is equal to the block size we specified
        context = context[1:] + [ix]

# and finally we  convert those lists into vectors, because that's what we use to work with matrices
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .


So up until now it's exactly the same that we were doing before, but instead of using bigrams (`block_size = 2`) we're using sets of $x_i$ (that will predict an output $y_i$) of arbitrary length.

We'll do the same but with all the words:

In [12]:
# # context length: how many characters do we take to predict the next one?
# block_size = 3
# X, Y = [], []

# for w in words:
#     # first we fill the context with all zeros (the character ".")
#     context = [0] * block_size

#     # we iterate over each character in the given word
#     for ch in w + ".":
#         # we get the index of the character
#         ix = ctoi[ch]
#         # and given the existing context that we have (i.e. previous characters that we read in this word),
#         # we use that pair context-character to create an X-Y value in our dataset (input-output)
#         X.append(context)
#         # (remember that context is a set of indexes as well)
#         Y.append(ix)
#         # finally, we append this given character to the context and slice that context so that its size
#         # is equal to the block size we specified
#         context = context[1:] + [ix]

# # and finally we  convert those lists into vectors, because that's what we use to work with matrices
# X = torch.tensor(X)
# Y = torch.tensor(Y)

In [13]:
print(X.shape, X.dtype)
print(Y.shape, Y.dtype)

torch.Size([25, 3]) torch.int64
torch.Size([25]) torch.int64


Viendo la forma que tienen estos tensores, tiene sentido.

In [14]:
X[:10]

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22]])

In [15]:
Y[:10]

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9])

## Embedding

An embedding gives the NN a **compact** and **learnable** representation of each character, even being able to establish similarities between characters. With the one hot encoding approach we were just fixing the representation, making it arbitrarily bigger and avoiding any possible learnability there.

Furthermore, you're separating the two concerns that we were mixing in our previous approach with one hot encoded vectors: the embedding learns how to *represent* those characters, and the first layer learns what to *do* with those characters.

Also, we have to take into account that the dimension of the vectors that we'll input into the NN will determine directly the size of the first weight matrix (remember that the first layer's weights are $W \in \mathbb{R}^{n \times h}$, where $n$ is the input dimension and $h$ the number of neurons that we want for that layer), so if we use a smaller input vector (e.g. two dimensional embedding vs a $3 \text{ context length} \times 27 \text{ possible characters} = 81$ one hot encoded vector) we'll be doing less computation.

We initialize the embeddings from random numbers. We selected 2 to be the number of dimensions that we want.

In [16]:
C = torch.randn((27, 2))

> Note: here he makes an argument that we could interpret this first *"take the value of C with index equivalent to that of our character"* (i.e. picking the embedding for each character) as a first layer to which we don't apply an activation function, making them linear. This happens because a one hot encoding vector times a matrix is just picking a specific row from that matrix, which is equivalent to indexing. This means that we have just moved backwards the one hot encoding process and the embedding could be seen as "another layer" which doesn't have an activation function.

In [17]:
C.shape

torch.Size([27, 2])

In [18]:
C.dtype

torch.float32

In [19]:
C

tensor([[ 0.7254,  0.2741],
        [-0.5639,  1.1605],
        [-0.1210,  0.8862],
        [ 0.7692,  1.8552],
        [-0.7267, -0.8086],
        [-1.4119,  0.5947],
        [-0.3329,  1.0693],
        [-0.6358,  1.1209],
        [ 0.5579,  0.3222],
        [ 1.1512, -0.6868],
        [-0.3857, -0.8312],
        [ 0.4072,  0.7057],
        [-0.7296,  1.6341],
        [ 0.1350, -1.6807],
        [ 0.0809,  2.5129],
        [ 0.1605, -0.1566],
        [ 0.0378, -0.5097],
        [ 0.1352, -0.4372],
        [ 0.9187, -0.4175],
        [-0.0247, -0.0990],
        [-1.7194, -0.9916],
        [ 0.8706,  0.4259],
        [-1.4397, -0.8618],
        [-0.0359, -0.3963],
        [-1.7087, -0.4114],
        [ 0.0661, -0.3970],
        [-1.1355, -1.1825]])

So the embedding vector corresponding to the character `f`, for example, would be:

In [20]:
C[ctoi["f"]]

tensor([-0.3329,  1.0693])

What we'll do now is leverage PyTorch indexing capabilities, and basically create a new tensor which contains each embedding that corresponds to each character in `X`:

In [21]:
X.shape

torch.Size([25, 3])

In [22]:
C[X].shape

torch.Size([25, 3, 2])

(and we know that there'll be only 27 unique values in that tensor)

We can see how this coincides in action:

In [23]:
X[13, 2]

tensor(1)

In [24]:
C[X][13, 2]

tensor([-0.5639,  1.1605])

In [25]:
C[1]

tensor([-0.5639,  1.1605])

Super.

In [26]:
embedding = C[X]

In [31]:
embedding.shape

torch.Size([25, 3, 2])

## Constructing the hidden layer

Given that we have `3 embeddings x 2 dimensions = 6`, we have to initialize a matrix of weights of dimension `(6 x n)`, where `n` is the number of neurons we want in that first hidden layer. Just to recap: each neuron will have `6` weights associated with it. Let's pick 100, arbitrary decision.

In [27]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

We would like to do `emd @ W1 + b1`, but right now the shapes don't match:

In [28]:
embedding.shape

torch.Size([25, 3, 2])

In [29]:
W1.shape

torch.Size([6, 100])

We want to "concatenate" the embeddings so that they are `(25 x 6)`. We can do this in several ways, for example using `torch.cat`:

In [33]:
embedding

tensor([[[ 0.7254,  0.2741],
         [ 0.7254,  0.2741],
         [ 0.7254,  0.2741]],

        [[ 0.7254,  0.2741],
         [ 0.7254,  0.2741],
         [-1.4119,  0.5947]],

        [[ 0.7254,  0.2741],
         [-1.4119,  0.5947],
         [ 0.1350, -1.6807]],

        [[-1.4119,  0.5947],
         [ 0.1350, -1.6807],
         [ 0.1350, -1.6807]],

        [[ 0.1350, -1.6807],
         [ 0.1350, -1.6807],
         [-0.5639,  1.1605]],

        [[ 0.7254,  0.2741],
         [ 0.7254,  0.2741],
         [ 0.7254,  0.2741]],

        [[ 0.7254,  0.2741],
         [ 0.7254,  0.2741],
         [ 0.1605, -0.1566]],

        [[ 0.7254,  0.2741],
         [ 0.1605, -0.1566],
         [-0.7296,  1.6341]],

        [[ 0.1605, -0.1566],
         [-0.7296,  1.6341],
         [ 1.1512, -0.6868]],

        [[-0.7296,  1.6341],
         [ 1.1512, -0.6868],
         [-1.4397, -0.8618]],

        [[ 1.1512, -0.6868],
         [-1.4397, -0.8618],
         [ 1.1512, -0.6868]],

        [[-1.4397, -0

In [34]:
# con esto pillamos:
# - todas las filas
# - solo la primera columna
# - el vector 2D entero de esa primera "celda" de la primera columna
embedding[:, 0, :]

tensor([[ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [-1.4119,  0.5947],
        [ 0.1350, -1.6807],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 0.1605, -0.1566],
        [-0.7296,  1.6341],
        [ 1.1512, -0.6868],
        [-1.4397, -0.8618],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [-0.5639,  1.1605],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 0.7254,  0.2741],
        [ 1.1512, -0.6868],
        [-0.0247, -0.0990],
        [-0.5639,  1.1605],
        [-0.1210,  0.8862],
        [-1.4119,  0.5947],
        [-0.7296,  1.6341]])

In [35]:
torch.cat([embedding[:, 0, :], embedding[:, 1, :], embedding[:, 2, :]], 1).shape

torch.Size([25, 6])

There's a more scalable solution: `unbind`.

In [37]:
# this gives us exactly what we achieved before, because unbind returns the slices along a given
# dimension (like "splitting" a tensor into multiple other tensors)
torch.cat(torch.unbind(embedding, 1), 1).shape

torch.Size([25, 6])

But there's an even LEANER approach to this, and it makes sense to use it. 

Pytorch sees tensors as **one dimensional arrays** with some special properties that represent its size and other things (in order to know more about [Pytorch Internals](https://blog.ezyang.com/2019/05/pytorch-internals/), check that blog post from ezyang) (storage offset, strides and shapes). We can check it out with:

In [47]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [48]:
a.shape

torch.Size([18])

In [49]:
a.view(2, 9)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [50]:
a.view(3, 3, 2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [51]:
a.view(3, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])

In [54]:
a.view(3, 6).storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

So whenever we are manipulating the view of a tensor, it's an extremely efficient operation because no memory for the values of the tensor is being modified (no copies, etc.).

This means we can do:

In [56]:
embedding.view(25, 6)

tensor([[ 0.7254,  0.2741,  0.7254,  0.2741,  0.7254,  0.2741],
        [ 0.7254,  0.2741,  0.7254,  0.2741, -1.4119,  0.5947],
        [ 0.7254,  0.2741, -1.4119,  0.5947,  0.1350, -1.6807],
        [-1.4119,  0.5947,  0.1350, -1.6807,  0.1350, -1.6807],
        [ 0.1350, -1.6807,  0.1350, -1.6807, -0.5639,  1.1605],
        [ 0.7254,  0.2741,  0.7254,  0.2741,  0.7254,  0.2741],
        [ 0.7254,  0.2741,  0.7254,  0.2741,  0.1605, -0.1566],
        [ 0.7254,  0.2741,  0.1605, -0.1566, -0.7296,  1.6341],
        [ 0.1605, -0.1566, -0.7296,  1.6341,  1.1512, -0.6868],
        [-0.7296,  1.6341,  1.1512, -0.6868, -1.4397, -0.8618],
        [ 1.1512, -0.6868, -1.4397, -0.8618,  1.1512, -0.6868],
        [-1.4397, -0.8618,  1.1512, -0.6868, -0.5639,  1.1605],
        [ 0.7254,  0.2741,  0.7254,  0.2741,  0.7254,  0.2741],
        [ 0.7254,  0.2741,  0.7254,  0.2741, -0.5639,  1.1605],
        [ 0.7254,  0.2741, -0.5639,  1.1605, -1.4397, -0.8618],
        [-0.5639,  1.1605, -1.4397, -0.8

Going back to the operation that we wanted before (`emd @ W1 + b1`), we can achieve that with:

In [59]:
# using -1 in the first dimension will make pytorch guess what it should be so that the numbers match
h = embedding.view(-1, 6) @ W1 + b1

In [58]:
h.shape

torch.Size([25, 100])

These are the **hidden states**, the activations of each neuron (100 neurons for each of the given input examples `X[i]`).

Also, we can review that the correct thing is happening with the hidden states:

In [60]:
(embedding.view(-1, 6) @ W1).shape

torch.Size([25, 100])

In [62]:
b1.shape

torch.Size([100])

So pytorch will broadcast `b1` as a vector of:
```
25, 100
 1, 100
```
and it'll repeat each element in its first dimension 25 times. 

(This is done knowing about broadcasting rules, which I'm not an expert of and I don't know if I want to be).

## Implementing the output layer

Following the same logic as before (review the formal definition of NN if this is not clear), we need a layer of `(100 x n)`, where `n` is the number of neurons and thus the number of outputs. Given that we want this layer to be the final one, `n = 27`. 

In [63]:
W2 = torch.randn((100, 27))
b2 = torch.randn(27)

In [64]:
logits = h @ W2 + b2

In [65]:
logits.shape

torch.Size([25, 27])

Logits is the name that we give the actual "raw output" of our final layer, upon which we'll apply softmax later on in order to get a proper mathematical interpretation out of it (probability distribution).

> *A note on logits and their interpretability:*
> 
> When we get the final result of our NN `(h @ W2 + b2)`, we get a 27 dimensional array of either positive, negative, big or small numbers. We can't make an interpretation out of them. That's why we run a **softmax** operation on them, because softmax enforces that distribution of numbers to behave like a distribution of probabilities (all between 0 and 1, and all sum 1).

In [66]:
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True)

Note that we're calling that `counts` because given the mathematical interpretation that we're taking of the final output thanks to the softmax, the `exp` takes the same place structurally as the counts took earlier. 

We **can't** get to the same place as we did in the bigram lesson, in which by using the statistical approach and the NN approach we arrived at the same conclusion because by using embeddings (i.e. representing input characters by 2 dimensional vectors instead of one-hot encoded vectors of 27 dimensions) we're reducing the free parameters that we wrangle, so we can't achieve that perfect match, but we're getting the benefit of **generalization**, and unseen examples that behave similar to seen examples are going to get nice probability distributions, contrary to the statistical approach, in which we would be fucked for unseen examples. 

Trying to take the statistical approach when we have more possible contexts than training examples (e.g. we have ~200k characters and for a 5-gram (4 chars of context) we'd have $27^4 = 531,000$ possible contexts) is what is called the *curse of dimensionality* or *data sparsity*. I discussed this in detail with Claude.

(min. 30:49)